project:
  type: website
  render: 
      - '*.qmd'
      - '!code/'
      - '!old_stuff/'
      - '!raw_posts/'
  # output-dir: .
website: 
  title: "Michael Clark"
  description: |
    "Statistics, Data, Science"
  site-url: https://m-clark.github.io
  navbar:
    right:
      - about.qmd
      - documents.qmd
      - code.qmd
    left:
      - icon: linkedin
        # text: LinkedIn
        href: https://www.linkedin.com/in/michael-clark-b475b5170/
      - icon: github
        # text: Github
        href: https://github.com/m-clark
      # - icon: bluesky no icon after 2 years of requests
      - text: BlueSky 
        href: https://bsky.app/profile/m-clark.bsky.social
      - icon: twitter-x
        # text: X
        href: https://x.com/statsdatasci
      - icon: rss
        href: index.xml
    background: gray
    foreground: '#fff'  # this will change generated navbar 'icons' and similar
    twitter-card: true
    open-graph: true
    favicon: img/mc_logo.png
    logo: img/mc_logo.png
format:
  html:
    theme: 
      - sandstone
      # - styles.css
      - custom.scss
    mainfont: Source Sans 3
    monofont: Roboto Mono
    fontsize: 1rem
    linkcolor: '#1f77b4'
    code-block-bg: '#FAFAFA80'
    grid: 
    # https://quarto.org/docs/output-formats/page-layout.html#grid-customization
      body-width: 1000px
      # margin-width: 250px
      # sidebar-width: 300px
# misc
# margin-header: |
#   ![](/img/mc_logo.png){width=100px}

license: 'CC BY-SA'

# Default author
# author:
#   - name: Michael Clark
#     url: https://m-clark.github.io
#     affiliation: Strong Analytics
#     affiliation-url: https://strong.io

# Default fields for citation
citation: true

