---
title: Odds / Ends
---

Here you'll find things that just don't fit elsewhere, especially things I do for fun or personal interest. 


## R Packages


<span itemscope itemtype ="http://schema.org/WebApplication">
[<span itemprop="name">visibly</span>](https://m-clark.github.io/visibly/)     
<span itemprop="description">
This is a collection of functions that I use related to visualization, e.g. the palette generating function (create_palette) and clean visualization themes for ggplot and plotly.  In additon, there are visualizations specific to mixed and additive models.
</span>
</span>


<span itemscope itemtype ="http://schema.org/WebApplication">
[<span itemprop="name">tidyext</span>](https://m-clark.github.io/tidyext/)     
<span itemprop="description">
This package is a collection of functions that do the things I commonly need to do with data while doing other processing within the dataverse. I work with data for myself and others everyday, and use these functions quite often.
</span>
</span>


<span itemscope itemtype ="http://schema.org/WebApplication">
[<span itemprop="name">lazerhawk</span>](https://github.com/m-clark/lazerhawk/)     
<span itemprop="description">
While the name is more or less explanatory, to clarify, this is a package of miscellaneous functions that are mostly useful to me. 
</span>
</span>


<span itemscope itemtype ="http://schema.org/WebApplication">
[<span itemprop="name">198R</span>](https://github.com/m-clark/NineteenEightyR/)     
<span itemprop="description">
R with its collar flipped, or the movie Drive if it was all about R programming, writing R code on a beach in Miami as the sun sets, R wearing sunglasses at night, R asking you to take it home tonight because it doesn't want to let you go until you see the light, Countach > Testarrosa, but Delorean > all except R, R if Automan had lasted longer than 1 season, driving down Mulholland Dr. at night thinking about R code, R playing a cello at the end of a dock on a lake before taking a ride in a badass helicopter, R with its hair all done up with Aquanet... You get the idea. 
</span>
</span>


<span itemscope itemtype ="http://schema.org/WebApplication">
[<span itemprop="name">538 football club rankings</span>](https://m-clark.github.io/five38clubrankings/)     
<span itemprop="description">
This package grabs the table located at [538](https://projects.fivethirtyeight.com/global-club-soccer-rankings/), and additionally does some summary by league and country. 
</span>
</span>


In addition to these, though they are not publicly available, I've created even more involved packages for specific project work.

## Shiny Apps

<span itemscope itemtype ="http://schema.org/WebApplication">
[<span itemprop="name">Historical Football Data</span>](http://micl.shinyapps.io/football/)     
<span itemprop="description">My annual dive into the frustration of Shiny has produced an [app to explore historical football/soccer data](https://micl.shinyapps.io/football/) for various European leagues (<span itemprop="keywords">Premier</span>, <span itemprop="keywords">La Liga</span>, <span itemprop="keywords">Serie A</span> etc.) and <span itemprop="keywords">MLS</span>. One can create tables for a given country/league and year selected, with some leagues having multiple tiers available, and stretching back many decades.  Beyond that, one can get a specific team's historical finishing position, league games for a specific season, all-time tables, and all-time head-to-head results (within a league).
</span>
</span>


<span itemscope itemtype ="http://schema.org/WebApplication">
[<span itemprop="name">Bayesian Demonstration</span>](http://micl.shinyapps.io/prior2post/)     
<span itemprop="description">A simple interactive demonstration for those just starting on their <span itemprop="keywords">Bayesian</span> journey.
</span>
</span>

<span itemscope itemtype ="http://schema.org/WebApplication">
[<span itemprop="name">A History of Tornados</span>](http://micl.shinyapps.io/tornados/)     
<span itemprop="description">Because I had too much time on my hands and wanted to try out the <span itemprop="keywords">dashboard</span> feature of <span itemprop="keywords">R Markdown</span>.  Maps <span itemprop="keywords">tornado</span> activity from 1950-2015.  At some point I'll go back and fix the lag issue, but otherwise it's interesting data.
</span>
</span>

<span itemscope itemtype ="http://schema.org/ScholarlyArticle http://schema.org/TechArticle">
[<span itemprop="name">Last Statements of the Texas Executed</span>](http://micl.shinyapps.io/texEx/texEx.Rmd)     
<span itemprop="description">A demonstration of both <span itemprop="keywords">text analysis</span> and <span itemprop="keywords">literate programming</span>/document generation with a dynamic and interactive research document. The texts regard the last statements of offenders in Texas.
</span>
</span>