---
title: Resources
output:
  distill::distill_article:
    toc: true
---

This is a list of resources for myself primarily, essentially a reminder of things to check out from time to time, or links I've gone back to on more than one occasion.  


## R


- [Use R series](http://www.springer.com/series/6991)
<!-- : for umich folks, this is electronically [available](https://link-springer-com.proxy.lib.umich.edu/bookseries/6991) -->
- [Ropensci](https://ropensci.org/) Packages for Open Science.
- [GitHub trending](https://github.com/trending/r)
- [R Views](https://rviews.rstudio.com/)
- [RStudio Blog](https://www.rstudio.com/blog/)

## Stan

- [Discourse](http://discourse.mc-stan.org/)
- [Example models](https://github.com/stan-dev/example-models/)


## Python

- [Fast AI](fast.ai) Teaching and tools for deep learning
- [Statsmodels](http://www.statsmodels.org/stable/index.html) Standard statistical models in Python
- [Scikit-learn](http://scikit-learn.org/stable/)  Simple and efficient tools for data mining and data analysis
- [Pandas](http://pandas.pydata.org/) Dealing with data in an R-like way
<!-- - [Workshops](http://kshedden.github.io/) Kerby Shedden's workshop notes -->
<!-- - [Workshops](http://marcio-mourao.github.io) Marcio's workshop notes -->
<!-- - [NLTK](http://www.nltk.org/) -->
- [gensim](https://radimrehurek.com/gensim/)



## People, Blogs etc.

- [Andrew Gelman](http://andrewgelman.com/)
- [Cosma Shalizi](http://bactra.org/weblog/)
- [RStudio](https://blog.rstudio.org/)
- [R-bloggers](https://www.r-bloggers.com/)
- [R Views](https://rviews.rstudio.com/)
- [Chris Colah](https://colah.github.io/)
- [Christian Robert](https://xianblog.wordpress.com/)
- [Awesome List for Machine Learning](https://github.com/josephmisiti/awesome-machine-learning)
- [Frank Harrell](http://www.fharrell.com/)



<!-- ## SEM -->

<!-- - [Pearl](http://bayes.cs.ucla.edu/jp_home.html) -->
<!-- - [Imai](http://imai.princeton.edu/) -->
<!-- - [Mplus forums](https://www.statmodel.com/cgi-bin/discus/discus.cgi) -->
<!-- - [Mplus manual](https://www.statmodel.com/download/usersguide/MplusUserGuideVer_8.pdf) -->



## Miscellaneous

- [Distill](http://distill.pub/)
- [Mixed Model FAQ](https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html)
- [Factor Analysis vs. Principal Component Analysis](http://stats.stackexchange.com/questions/1576/what-are-the-differences-between-factor-analysis-and-principal-component-analysi)
<!-- - [dplyr vs. data.table](https://stackoverflow.com/questions/21435339/data-table-vs-dplyr-can-one-do-something-well-the-other-cant-or-does-poorly/27840349#27840349) -->



## Free Books

### Stats

- [Deep Learning Book](http://www.deeplearningbook.org/) Goodfellow et al.
- [Elements of Statistical Learning](http://statweb.stanford.edu/~tibs/ElemStatLearn/) Bible of ML by Hastie, Tibshirani, & Friedman.
- [Introduction to Statistical Learning](http://www-bcf.usc.edu/~gareth/ISL/) Application of the above in R.
- [Computer Age Statistical Inference](https://web.stanford.edu/~hastie/CASI/) Efron & Hastie.
- [Advanced Data Analysis from an Elementary Point of View](http://www.stat.cmu.edu/~cshalizi/ADAfaEPoV/)
- [Gaussian Processes for Machine Learning](http://www.gaussianprocess.org/gpml/) Carl Rasmussen
- [Discrete Choice Methods with Simulation](http://eml.berkeley.edu/books/choice2.html) Kenneth Train
- [An Introduction to Psychometric Theory with Applications in R](http://www.personality-project.org/r/book/)


### Programming

- [Advanced R](http://adv-r.had.co.nz/)  Hadley Wickham
- [R for Data Science](http://r4ds.had.co.nz/) Hadley Wickham
- [R Packages](http://r-pkgs.had.co.nz/)  Hadley Wickham
- [Bookdown website](https://bookdown.org/) All R related
- [Happy Git and GitHub for the useR](http://happygitwithr.com/)
