---
title: Workshops
creative_commons: CC BY
---

Here you'll find workshop slides and similar.  They are roughly in order of how recently they've been given (or will be).  Some are not so much workshops as talks without any expectation of hands-on exercises or similar.  Check out the [schedule](http://cscar.research.umich.edu/events/category/workshops/) to see times/dates for these as well as other CSCAR events (we give a lot of workshops!).


## Recent talks...

If you're looking for the notes for a recent workshop I've given, you'll find it here.


<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">Data Processing and Visualization in R</span>](../data-processing-and-visualization/)     
Focus is on common <span itemprop="keywords">data processing</span> and exploration techniques, especially as a prelude to <span itemprop="keywords">visualization</span>.  Part of the focus will be on <span itemprop="keywords">dplyr</span> and <span itemprop="keywords">tidyverse</span>, which enhance and facilitate the sorts of operations that typically arise when dealing with data, including faster <span itemprop="keywords">I/O</span> and grouped operations.  For visualization, the focus will be on using <span itemprop="keywords">ggplot2</span> and other packages that allow for interactivity. Exercises may be found in the document as well (including [Jupyter notebooks](https://github.com/m-clark/data-processing-and-visualization/tree/master/code) of the same demonstrations in Python).
</span>

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">Introduction to R Markdown</span>](../Introduction-to-Rmarkdown/)     
This workshop will introduce participants to the basics of <span itemprop="keywords">R Markdown</span>. After an introduction to concepts related to <span itemprop="keywords">reproducible programming and research</span>, demonstrations of standard <span itemprop="keywords">markdown</span> as well as overviews of different formats will be provided, including exercises.
</span>

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">Factor Analysis and Related Methods</span>](../sem/FA_notes.html)     
This workshop will expose participants to a variety of related techniques that might fall under the heading of ‘<span itemprop="keywords">factor analysis</span>’, <span itemprop="keywords">latent variable modeling</span>, <span itemprop="keywords">dimension reduction</span> and similar, such as <span itemprop="keywords">principal components analysis</span>, <span itemprop="keywords">factor analysis</span>, and <span itemprop="keywords">measurement models</span>, with possible exposure to and demonstration of <span itemprop="keywords">latent Dirichlet allocation</span>, <span itemprop="keywords">mixture models</span>, <span itemprop="keywords">item response theory</span>, and others.  Brief overviews with examples of the more common techniques will be provided.
</span>

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">Text Analysis with R</span>](../text-analysis-with-R/)  
This document covers a wide range of topics, including how to process text generally, and demonstrations of <span itemprop="keywords">sentiment analysis</span>, <span itemprop="keywords">parts-of-speech tagging</span>, and <span itemprop="keywords">topic modeling</span>.  Exercises are provided for some topics.  Some Python examples will also be added at some point.
</span>

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">Mixed Models with R</span>](../mixed-models-with-R/)  
This workshop focuses on <span itemprop="keywords">mixed effects models using R</span>, covering basic <span itemprop="keywords">random effects</span> models (<span itemprop="keywords">random intercepts and slopes</span>) as well as extensions into <span itemprop="keywords">generalized mixed models</span> and discussion of realms beyond.
</span>

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name keywords">Structural Equation Modeling</span>](../sem/)  
This document regards a recent workshop given on <span itemprop="keywords">structural equation modeling</span>.  It is conceptually based, and tries to generalize beyond the standard SEM treatment. The document should be useful to anyone interested in the techniques covered, though it is R-based, with special emphasis on the [<span itemprop="keywords">lavaan</span>](http://lavaan.ugent.be/) package.
</span>



## Been awhile...

These haven't been given in at least a year or so. The content is still likely useful, but until updated or given again, you may also find a more fully fleshed out related work on the [documents](../documents) page.

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">My God, it's full of STARs! Using astrology to get more from your data.</span>](../workshops/stars/)  
Talk on <span itemprop="keywords">structured additive regression</span> models, and <span itemprop="keywords">generalized additive models</span> in particular.
</span>

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name keywords">Become a Bayesian in 10 Minutes</span>](../workshops/bayesian/)  
This document regards a talk aimed at giving an introduction <span itemprop="keywords">Bayesian modeling</span> in <span itemprop="keywords">R</span> via the <span itemprop="keywords">Stan</span> programming language.  It doesn't assume too much statistically or any prior Bayesian experience.  For those with such experience, they can quickly work with the code or packages discussed.  I post them here because they exist and provide a quick overview, but you'd get more from the more extensive [document](../bayesian-basics/).
</span>

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name keywords" style="font-variant:small-caps;">Engaging the Web with R</span>](../docs/web)     
<span itemprop="description">Document regarding the use of R for <span itemprop="keywords">web scraping</span>, extracting data via an <span itemprop="keywords">API</span>, <span itemprop="keywords">interactive</span> web-based <span itemprop="keywords">visualizations</span>, and producing <span itemprop="keywords">web-ready documents</span>.  It serves as an overview of ways one might start to use R for web-based activities as opposed to a hand-on approach.
</span>
</span>

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">Ceci n’est pas une %>%</span>](../workshops/dplyr/mainSlides.html)      
Exploring your data with <span itemprop="keywords">R</span>. A workshop that introduces some newer modes of <span itemprop="keywords">data wrangling</span> within R, with an eye toward <span itemprop="keywords">visualization</span>. Focus on <span itemprop="keywords">dplyr</span> and <span itemprop="keywords">magrittr</span> packages.
</span>

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">Getting More from RStudio</span>](../workshops/introRstudio.html)    
An afternoon talk on how to use <span itemprop="keywords">RStudio</span> for more than just coding.
</span>



## Possible future topics

<span itemprop="keywords">Shiny</span> basics



## Other

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">R Bootcamp</span>](../workshops/r_bootcamp/master.html)    
An afternoon workshop I hope to develop further at some point.
</span>
