---
title: Workshops
toc: true
---

I used to give workshops regularly when I worked in academia, and I have kept the content here in case anyone who attended wanted to refer back to them. Some were not so much workshops as talks without any expectation of hands-on exercises or similar, so may not be as useful without the in-person context. Some of these, especially programming specific ones, are likely too dated to be useful beyond conceptual content, but the modeling focused ones may still have mostly relevant content.



## Recent

- [Polars](https://github.com/m-clark/polars-talk-2024): A notebook and related content providing an overview of polars with comparison to pandas and R package approaches like [data.table]{.pack}.

I also have given internal talks on Media Mix Modeling and Models for Tabular Data at our yearly in-person gatherings.

## Previous efforts


These were among the last workshops I gave before leaving academia.

- [Distill for R Markdown](https://m-clark.github.io/distill-workshop/)
- [Exploratory Data Analysis Tools](https://m-clark.github.io/exploratory-data-analysis-tools/)
- [Mixed Models with R](../mixed-models-with-R/)
- [More Mixed Models](https://github.com/m-clark/more-mixed-models-2019)
- [Patchwork and gganimate](https://github.com/m-clark/patchmate-2019)
- [Library Learning Analytics Workshop](https://github.com/m-clark/LLAP-2019)
- [Getting More from RStudio](/workshops/introRstudio.html)
- [Latent Variable Models](https://github.com/m-clark/latent-variable-models-workshop-2019)
- [Generalized Additive Models](https://github.com/m-clark/generalized-additive-models-workshop-2019)
- [Mixed Models](https://github.com/m-clark/mixed-models-with-r-workshop-2019)


### Texts

These are the texts that serve as the basis for the workshops. At least a few of these were more recently updated.


<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">Practical Data Science</span>](../data-processing-and-visualization/)     
Focus is on common <span itemprop="keywords">data science</span>  tools and techniques in R, including data processing, programming, modeling, visualization, and presentation of results. Exercises may be found in the document, and demonstrations of most content in Python is available via [Jupyter notebooks](https://github.com/m-clark/data-processing-and-visualization/tree/master/jupyter_notebooks).
</span>


<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">Mixed Models with R</span>](../mixed-models-with-R/)  
This workshop focuses on <span itemprop="keywords">mixed effects models using R</span>, covering basic <span itemprop="keywords">random effects</span> models (<span itemprop="keywords">random intercepts and slopes</span>) as well as extensions into <span itemprop="keywords">generalized mixed models</span> and discussion of realms beyond.
</span>

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name keywords">Structural Equation Modeling</span>](../sem/)  
This document regards a recent workshop given on <span itemprop="keywords">structural equation modeling</span>.  It is conceptually based, and tries to generalize beyond the standard SEM treatment. The document should be useful to anyone interested in the techniques covered, though it is R-based, with special emphasis on the [<span itemprop="keywords">lavaan</span>](http://lavaan.ugent.be/) package.
</span>


<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">Easy Bayes with rstanarm and brms</span>](../easy-bayes/)     
This workshop provides an overview of the <span itemprop="keywords">rstanarm</span> and <span itemprop="keywords">brms</span> packages. Basic modeling syntax is provided, as well as diagnostic checking, model comparison (<span itemprop="keywords">posterior predictive checks</span> , <span itemprop="keywords">WAIC/LOO</span> ), and how to get more from the models (<span itemprop="keywords">marginal effects</span> , <span itemprop="keywords">posterior probabilities</span> posterior probabilities, etc.).
</span>


<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">Factor Analysis and Related Methods</span>](../sem/FA_notes.html)     
This workshop will expose participants to a variety of related techniques that might fall under the heading of ‘<span itemprop="keywords">factor analysis</span>', <span itemprop="keywords">latent variable modeling</span>, <span itemprop="keywords">dimension reduction</span> and similar, such as <span itemprop="keywords">principal components analysis</span>, <span itemprop="keywords">factor analysis</span>, and <span itemprop="keywords">measurement models</span>, with possible exposure to and demonstration of <span itemprop="keywords">latent Dirichlet allocation</span>, <span itemprop="keywords">mixture models</span>, <span itemprop="keywords">item response theory</span>, and others.  Brief overviews with examples of the more common techniques will be provided.
</span>

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">Introduction to R Markdown</span>](../Introduction-to-Rmarkdown/)     
This workshop will introduce participants to the basics of <span itemprop="keywords">R Markdown</span>. After an introduction to concepts related to <span itemprop="keywords">reproducible programming and research</span>, demonstrations of standard <span itemprop="keywords">markdown</span> as well as overviews of different formats will be provided, including exercises.  This document has been superseded by Practical Data Science, and will no longer be updated.
</span>


<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">Text Analysis with R</span>](../text-analysis-with-R/)  
This document covers a wide range of topics, including how to process text generally, and demonstrations of <span itemprop="keywords">sentiment analysis</span>, <span itemprop="keywords">parts-of-speech tagging</span>, and <span itemprop="keywords">topic modeling</span>.  Exercises are provided for some topics. It has practically no relevance in the modern large language model era.
</span>



## Been awhile...

These haven't been given recently and are increasingly out date, but some content may be useful. 

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">My God, it's full of STARs! Using astrology to get more from your data.</span>](https://github.com/m-clark/stars)
Talk on <span itemprop="keywords">structured additive regression</span> models, and <span itemprop="keywords">generalized additive models</span> in particular.
</span>

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name keywords">Become a Bayesian in 10 Minutes</span>](https://github.com/m-clark/easy-bayes)
This document regards a talk aimed at giving an introduction <span itemprop="keywords">Bayesian modeling</span> in <span itemprop="keywords">R</span> via the <span itemprop="keywords">Stan</span> programming language.  It doesn't assume too much statistically or any prior Bayesian experience.  For those with such experience, they can quickly work with the code or packages discussed.  I post them here because they exist and provide a quick overview, but you'd get more from the more extensive [document](../bayesian-basics/).
</span>

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name keywords" style="font-variant:small-caps;">Engaging the Web with R</span>](https://github.com/m-clark/webR)
<span itemprop="description">Document regarding the use of R for <span itemprop="keywords">web scraping</span>, extracting data via an <span itemprop="keywords">API</span>, <span itemprop="keywords">interactive</span> web-based <span itemprop="keywords">visualizations</span>, and producing <span itemprop="keywords">web-ready documents</span>.  It serves as an overview of ways one might start to use R for web-based activities as opposed to a hand-on approach.
</span>
</span>

<span itemscope itemtype ="http://schema.org/TechArticle">
[<span itemprop="name">Ceci n'est pas une %>%</span>](https://github.com/m-clark/data-manipulation-in-r)
Exploring your data with <span itemprop="keywords">R</span>. A workshop that introduces some newer modes of <span itemprop="keywords">data wrangling</span> within R, with an eye toward <span itemprop="keywords">visualization</span>. Focus on <span itemprop="keywords">dplyr</span> and <span itemprop="keywords">magrittr</span> packages. No longer available as the javascript the slides were based on kept producing vulnerabilities for my website. Nowadays, using pipes is standard anyway.
</span>

