---
title: "Comparing means with lavaan"
description: |
  Comparing means and intercepts of latent variables
author:
  - name: Michael Clark
    url: https://m-clark.github.io
date: '`r format(Sys.Date(), "%B %d, %Y")`'
preview: ../../img/198R.png   # apparently no way to change the size displayed via css (ignored) or file (stretched)
output:
  distill::distill_article:
    self_contained: false
    toc: true
    css: ../../test.css
draft: true
tags: [R, factor analysis, growth curve, structural equation modeling, SEM, intercepts, means]
---


```{r}
library(tidyverse)
library(lavaan)

HS.model1 <- ' 
  visual  =~ x1 + x2 + x3
  textual =~ x4 + x5 + x6
  speed   =~ x7 + x8 + x9 
  
  
  # intercepts: in order to have an identified model, you would have to fix the
  # intercepts of observed to 0
  x1 ~ 0*1   

  visual ~  c(a, b)*1

   
  # comparisons
   diff := a - b
'
HS.model2 <- ' 
  visual  =~ x1 + x2 + x3
  textual =~ x4 + x5 + x6
  speed   =~ x7 + x8 + x9 
  
  
  # intercepts: but the above would be identical to comparing the intercepts on
  # whichever observed variable you previously fixed to zero
  x1 ~ c(a, b)*1   
   
  # comparisons
   diff := a - b
'

fit1 <- cfa(HS.model1, 
           data = HolzingerSwineford1939, 
           group = "school",
           meanstructure = T)
summary(fit1, std=T)

coef_1 = broom::tidy(fit1) %>% 
  filter(label != '')

coef_1


fit2 <- cfa(HS.model2, 
           data = HolzingerSwineford1939, 
           group = "school",
           meanstructure = T)
summary(fit2, std=T)
coef_2 = broom::tidy(fit2) %>% 
  filter(label != '')

coef_2
```


```{r}
HS.model3 <- ' 
  visual  =~ x1 + x2 + x3
  textual =~ x4 + x5 + x6
  speed   =~ x7 + x8 + x9 
  
  x1 ~ diff*school 
  x2 + x3 + x4 + x5 + x6 +  x7 + x8 + x9 ~ school
'
fit3 <- cfa(HS.model3, 
           data = HolzingerSwineford1939)
summary(fit3, std=T)
coef_3 = broom::tidy(fit3) %>% 
  filter(label == 'diff')

bind_rows(coef_1%>% 
  filter(label == 'diff'), 
  coef_2%>% 
  filter(label == 'diff'), coef_3) 
```

```{r measurement_invariance}
HS.model4 <- ' 
  visual  =~ x1 + x2 + x3
  textual =~ x4 + x5 + x6
  speed   =~ x7 + x8 + x9 

'
semTools::measurementInvariance(
  model = HS.model4, 
  data = HolzingerSwineford1939, 
  group = "school"
)
```


