---
title: "Long time no see..."
description: |
  New modeling book under way!
date: 2024-05-20
image:  ../../img/book_gp.svg  
draft: false
tags: [tabular data, linear models, machine learning, deep learning]
categories:
  - miscellaneous
---


## Book in progess

TLDR: [https://m-clark.github.io/book-of-models](https://m-clark.github.io/book-of-models)

Been a long time since I posted. Part of this was due to the fact that I had almost completely transferred my site to quarto, but then never got around to finishing it. That will happen eventually, and I will hopefully start posting again at that point.


But the real news is that I am working on a new book. It is a book on exploring models in data science, currently titled *Models Demystified*. In it, Seth Berry and I attempt to cover a wide range of models, from the simple to the complex, in a way that is accessible to those who are not experts in statistics or machine learning, or might be coming from one area and would like the basics in the other.  It covers quite a bit of ground, but tries to stick to the core what's necessary to get started doing *good enough* modeling. We're excited about it, and hope to have it out by the end of the year on CRC press in print, but you can [check it out now while it's in progress](https://m-clark.github.io/book-of-models). Hope you enjoy it!